// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/broker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskEvent_EventType int32

const (
	TaskEvent_EVENT_TYPE_UNSPECIFIED    TaskEvent_EventType = 0
	TaskEvent_EVENT_TYPE_NEW_TASK       TaskEvent_EventType = 1
	TaskEvent_EVENT_TYPE_TASK_UPDATED   TaskEvent_EventType = 2
	TaskEvent_EVENT_TYPE_TASK_CANCELLED TaskEvent_EventType = 3
)

// Enum value maps for TaskEvent_EventType.
var (
	TaskEvent_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_NEW_TASK",
		2: "EVENT_TYPE_TASK_UPDATED",
		3: "EVENT_TYPE_TASK_CANCELLED",
	}
	TaskEvent_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_NEW_TASK":       1,
		"EVENT_TYPE_TASK_UPDATED":   2,
		"EVENT_TYPE_TASK_CANCELLED": 3,
	}
)

func (x TaskEvent_EventType) Enum() *TaskEvent_EventType {
	p := new(TaskEvent_EventType)
	*p = x
	return p
}

func (x TaskEvent_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskEvent_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_broker_proto_enumTypes[0].Descriptor()
}

func (TaskEvent_EventType) Type() protoreflect.EnumType {
	return &file_api_proto_broker_proto_enumTypes[0]
}

func (x TaskEvent_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskEvent_EventType.Descriptor instead.
func (TaskEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{11, 0}
}

type SendTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAgent     string                 `protobuf:"bytes,1,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	ToAgent       string                 `protobuf:"bytes,2,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	Capability    string                 `protobuf:"bytes,3,opt,name=capability,proto3" json:"capability,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // JSON payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTaskRequest) Reset() {
	*x = SendTaskRequest{}
	mi := &file_api_proto_broker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskRequest) ProtoMessage() {}

func (x *SendTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskRequest.ProtoReflect.Descriptor instead.
func (*SendTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{0}
}

func (x *SendTaskRequest) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *SendTaskRequest) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *SendTaskRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *SendTaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTaskResponse) Reset() {
	*x = SendTaskResponse{}
	mi := &file_api_proto_broker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTaskResponse) ProtoMessage() {}

func (x *SendTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTaskResponse.ProtoReflect.Descriptor instead.
func (*SendTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{1}
}

func (x *SendTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SendTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_api_proto_broker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_api_proto_broker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        TaskStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=a2a.TaskStatus" json:"status,omitempty"`
	Result        []byte                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"` // JSON result (for completed)
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`   // Error message (for failed)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_api_proto_broker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *UpdateTaskRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_api_proto_broker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=a2a.TaskStatus" json:"status,omitempty"`
	FromAgent     string                 `protobuf:"bytes,2,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	ToAgent       string                 `protobuf:"bytes,3,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	Capability    string                 `protobuf:"bytes,4,opt,name=capability,proto3" json:"capability,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_api_proto_broker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{6}
}

func (x *ListTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *ListTasksRequest) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *ListTasksRequest) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *ListTasksRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *ListTasksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTasksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_api_proto_broker_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{7}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *ListTasksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CancelTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskRequest) Reset() {
	*x = CancelTaskRequest{}
	mi := &file_api_proto_broker_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskRequest) ProtoMessage() {}

func (x *CancelTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskRequest.ProtoReflect.Descriptor instead.
func (*CancelTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CancelTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTaskResponse) Reset() {
	*x = CancelTaskResponse{}
	mi := &file_api_proto_broker_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTaskResponse) ProtoMessage() {}

func (x *CancelTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTaskResponse.ProtoReflect.Descriptor instead.
func (*CancelTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{9}
}

func (x *CancelTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CancelTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_proto_broker_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type TaskEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         TaskEvent_EventType    `protobuf:"varint,1,opt,name=event,proto3,enum=a2a.TaskEvent_EventType" json:"event,omitempty"`
	Task          *Task                  `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEvent) Reset() {
	*x = TaskEvent{}
	mi := &file_api_proto_broker_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEvent) ProtoMessage() {}

func (x *TaskEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEvent.ProtoReflect.Descriptor instead.
func (*TaskEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{11}
}

func (x *TaskEvent) GetEvent() TaskEvent_EventType {
	if x != nil {
		return x.Event
	}
	return TaskEvent_EVENT_TYPE_UNSPECIFIED
}

func (x *TaskEvent) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type RouteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAgent     string                 `protobuf:"bytes,1,opt,name=from_agent,json=fromAgent,proto3" json:"from_agent,omitempty"`
	Capability    string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTaskRequest) Reset() {
	*x = RouteTaskRequest{}
	mi := &file_api_proto_broker_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTaskRequest) ProtoMessage() {}

func (x *RouteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTaskRequest.ProtoReflect.Descriptor instead.
func (*RouteTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{12}
}

func (x *RouteTaskRequest) GetFromAgent() string {
	if x != nil {
		return x.FromAgent
	}
	return ""
}

func (x *RouteTaskRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *RouteTaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type RouteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ToAgent       string                 `protobuf:"bytes,2,opt,name=to_agent,json=toAgent,proto3" json:"to_agent,omitempty"`
	Task          *Task                  `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteTaskResponse) Reset() {
	*x = RouteTaskResponse{}
	mi := &file_api_proto_broker_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteTaskResponse) ProtoMessage() {}

func (x *RouteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_broker_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteTaskResponse.ProtoReflect.Descriptor instead.
func (*RouteTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_broker_proto_rawDescGZIP(), []int{13}
}

func (x *RouteTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *RouteTaskResponse) GetToAgent() string {
	if x != nil {
		return x.ToAgent
	}
	return ""
}

func (x *RouteTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_api_proto_broker_proto protoreflect.FileDescriptor

const file_api_proto_broker_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/broker.proto\x12\x03a2a\x1a\x16api/proto/common.proto\"\x85\x01\n" +
	"\x0fSendTaskRequest\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x01 \x01(\tR\tfromAgent\x12\x19\n" +
	"\bto_agent\x18\x02 \x01(\tR\atoAgent\x12\x1e\n" +
	"\n" +
	"capability\x18\x03 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"J\n" +
	"\x10SendTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\x04task\x18\x02 \x01(\v2\t.a2a.TaskR\x04task\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"0\n" +
	"\x0fGetTaskResponse\x12\x1d\n" +
	"\x04task\x18\x01 \x01(\v2\t.a2a.TaskR\x04task\"\x83\x01\n" +
	"\x11UpdateTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12'\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0f.a2a.TaskStatusR\x06status\x12\x16\n" +
	"\x06result\x18\x03 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"3\n" +
	"\x12UpdateTaskResponse\x12\x1d\n" +
	"\x04task\x18\x01 \x01(\v2\t.a2a.TaskR\x04task\"\xc3\x01\n" +
	"\x10ListTasksRequest\x12'\n" +
	"\x06status\x18\x01 \x01(\x0e2\x0f.a2a.TaskStatusR\x06status\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x02 \x01(\tR\tfromAgent\x12\x19\n" +
	"\bto_agent\x18\x03 \x01(\tR\atoAgent\x12\x1e\n" +
	"\n" +
	"capability\x18\x04 \x01(\tR\n" +
	"capability\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"J\n" +
	"\x11ListTasksResponse\x12\x1f\n" +
	"\x05tasks\x18\x01 \x03(\v2\t.a2a.TaskR\x05tasks\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\",\n" +
	"\x11CancelTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"M\n" +
	"\x12CancelTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\x04task\x18\x02 \x01(\v2\t.a2a.TaskR\x04task\"-\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xd8\x01\n" +
	"\tTaskEvent\x12.\n" +
	"\x05event\x18\x01 \x01(\x0e2\x18.a2a.TaskEvent.EventTypeR\x05event\x12\x1d\n" +
	"\x04task\x18\x02 \x01(\v2\t.a2a.TaskR\x04task\"|\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13EVENT_TYPE_NEW_TASK\x10\x01\x12\x1b\n" +
	"\x17EVENT_TYPE_TASK_UPDATED\x10\x02\x12\x1d\n" +
	"\x19EVENT_TYPE_TASK_CANCELLED\x10\x03\"k\n" +
	"\x10RouteTaskRequest\x12\x1d\n" +
	"\n" +
	"from_agent\x18\x01 \x01(\tR\tfromAgent\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"f\n" +
	"\x11RouteTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bto_agent\x18\x02 \x01(\tR\atoAgent\x12\x1d\n" +
	"\x04task\x18\x03 \x01(\v2\t.a2a.TaskR\x04task2\xaa\x03\n" +
	"\rBrokerService\x127\n" +
	"\bSendTask\x12\x14.a2a.SendTaskRequest\x1a\x15.a2a.SendTaskResponse\x124\n" +
	"\aGetTask\x12\x13.a2a.GetTaskRequest\x1a\x14.a2a.GetTaskResponse\x12=\n" +
	"\n" +
	"UpdateTask\x12\x16.a2a.UpdateTaskRequest\x1a\x17.a2a.UpdateTaskResponse\x12:\n" +
	"\tListTasks\x12\x15.a2a.ListTasksRequest\x1a\x16.a2a.ListTasksResponse\x12=\n" +
	"\n" +
	"CancelTask\x12\x16.a2a.CancelTaskRequest\x1a\x17.a2a.CancelTaskResponse\x124\n" +
	"\tSubscribe\x12\x15.a2a.SubscribeRequest\x1a\x0e.a2a.TaskEvent0\x01\x12:\n" +
	"\tRouteTask\x12\x15.a2a.RouteTaskRequest\x1a\x16.a2a.RouteTaskResponseB,Z*github.com/Sithumli/Beacon/api/proto;protob\x06proto3"

var (
	file_api_proto_broker_proto_rawDescOnce sync.Once
	file_api_proto_broker_proto_rawDescData []byte
)

func file_api_proto_broker_proto_rawDescGZIP() []byte {
	file_api_proto_broker_proto_rawDescOnce.Do(func() {
		file_api_proto_broker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_broker_proto_rawDesc), len(file_api_proto_broker_proto_rawDesc)))
	})
	return file_api_proto_broker_proto_rawDescData
}

var file_api_proto_broker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_broker_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_broker_proto_goTypes = []any{
	(TaskEvent_EventType)(0),   // 0: a2a.TaskEvent.EventType
	(*SendTaskRequest)(nil),    // 1: a2a.SendTaskRequest
	(*SendTaskResponse)(nil),   // 2: a2a.SendTaskResponse
	(*GetTaskRequest)(nil),     // 3: a2a.GetTaskRequest
	(*GetTaskResponse)(nil),    // 4: a2a.GetTaskResponse
	(*UpdateTaskRequest)(nil),  // 5: a2a.UpdateTaskRequest
	(*UpdateTaskResponse)(nil), // 6: a2a.UpdateTaskResponse
	(*ListTasksRequest)(nil),   // 7: a2a.ListTasksRequest
	(*ListTasksResponse)(nil),  // 8: a2a.ListTasksResponse
	(*CancelTaskRequest)(nil),  // 9: a2a.CancelTaskRequest
	(*CancelTaskResponse)(nil), // 10: a2a.CancelTaskResponse
	(*SubscribeRequest)(nil),   // 11: a2a.SubscribeRequest
	(*TaskEvent)(nil),          // 12: a2a.TaskEvent
	(*RouteTaskRequest)(nil),   // 13: a2a.RouteTaskRequest
	(*RouteTaskResponse)(nil),  // 14: a2a.RouteTaskResponse
	(*Task)(nil),               // 15: a2a.Task
	(TaskStatus)(0),            // 16: a2a.TaskStatus
}
var file_api_proto_broker_proto_depIdxs = []int32{
	15, // 0: a2a.SendTaskResponse.task:type_name -> a2a.Task
	15, // 1: a2a.GetTaskResponse.task:type_name -> a2a.Task
	16, // 2: a2a.UpdateTaskRequest.status:type_name -> a2a.TaskStatus
	15, // 3: a2a.UpdateTaskResponse.task:type_name -> a2a.Task
	16, // 4: a2a.ListTasksRequest.status:type_name -> a2a.TaskStatus
	15, // 5: a2a.ListTasksResponse.tasks:type_name -> a2a.Task
	15, // 6: a2a.CancelTaskResponse.task:type_name -> a2a.Task
	0,  // 7: a2a.TaskEvent.event:type_name -> a2a.TaskEvent.EventType
	15, // 8: a2a.TaskEvent.task:type_name -> a2a.Task
	15, // 9: a2a.RouteTaskResponse.task:type_name -> a2a.Task
	1,  // 10: a2a.BrokerService.SendTask:input_type -> a2a.SendTaskRequest
	3,  // 11: a2a.BrokerService.GetTask:input_type -> a2a.GetTaskRequest
	5,  // 12: a2a.BrokerService.UpdateTask:input_type -> a2a.UpdateTaskRequest
	7,  // 13: a2a.BrokerService.ListTasks:input_type -> a2a.ListTasksRequest
	9,  // 14: a2a.BrokerService.CancelTask:input_type -> a2a.CancelTaskRequest
	11, // 15: a2a.BrokerService.Subscribe:input_type -> a2a.SubscribeRequest
	13, // 16: a2a.BrokerService.RouteTask:input_type -> a2a.RouteTaskRequest
	2,  // 17: a2a.BrokerService.SendTask:output_type -> a2a.SendTaskResponse
	4,  // 18: a2a.BrokerService.GetTask:output_type -> a2a.GetTaskResponse
	6,  // 19: a2a.BrokerService.UpdateTask:output_type -> a2a.UpdateTaskResponse
	8,  // 20: a2a.BrokerService.ListTasks:output_type -> a2a.ListTasksResponse
	10, // 21: a2a.BrokerService.CancelTask:output_type -> a2a.CancelTaskResponse
	12, // 22: a2a.BrokerService.Subscribe:output_type -> a2a.TaskEvent
	14, // 23: a2a.BrokerService.RouteTask:output_type -> a2a.RouteTaskResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_proto_broker_proto_init() }
func file_api_proto_broker_proto_init() {
	if File_api_proto_broker_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_broker_proto_rawDesc), len(file_api_proto_broker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_broker_proto_goTypes,
		DependencyIndexes: file_api_proto_broker_proto_depIdxs,
		EnumInfos:         file_api_proto_broker_proto_enumTypes,
		MessageInfos:      file_api_proto_broker_proto_msgTypes,
	}.Build()
	File_api_proto_broker_proto = out.File
	file_api_proto_broker_proto_goTypes = nil
	file_api_proto_broker_proto_depIdxs = nil
}
