// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/registry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchResponse_EventType int32

const (
	WatchResponse_EVENT_TYPE_UNSPECIFIED    WatchResponse_EventType = 0
	WatchResponse_EVENT_TYPE_REGISTERED     WatchResponse_EventType = 1
	WatchResponse_EVENT_TYPE_DEREGISTERED   WatchResponse_EventType = 2
	WatchResponse_EVENT_TYPE_UPDATED        WatchResponse_EventType = 3
	WatchResponse_EVENT_TYPE_HEALTH_CHANGED WatchResponse_EventType = 4
)

// Enum value maps for WatchResponse_EventType.
var (
	WatchResponse_EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_REGISTERED",
		2: "EVENT_TYPE_DEREGISTERED",
		3: "EVENT_TYPE_UPDATED",
		4: "EVENT_TYPE_HEALTH_CHANGED",
	}
	WatchResponse_EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_REGISTERED":     1,
		"EVENT_TYPE_DEREGISTERED":   2,
		"EVENT_TYPE_UPDATED":        3,
		"EVENT_TYPE_HEALTH_CHANGED": 4,
	}
)

func (x WatchResponse_EventType) Enum() *WatchResponse_EventType {
	p := new(WatchResponse_EventType)
	*p = x
	return p
}

func (x WatchResponse_EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WatchResponse_EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_registry_proto_enumTypes[0].Descriptor()
}

func (WatchResponse_EventType) Type() protoreflect.EnumType {
	return &file_api_proto_registry_proto_enumTypes[0]
}

func (x WatchResponse_EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WatchResponse_EventType.Descriptor instead.
func (WatchResponse_EventType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{13, 0}
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Endpoint      *Endpoint              `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Capabilities  []*Capability          `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Metadata      *Metadata              `protobuf:"bytes,6,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterRequest) GetEndpoint() *Endpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Agent         *Agent                 `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type DeregisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterRequest) Reset() {
	*x = DeregisterRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterRequest) ProtoMessage() {}

func (x *DeregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterRequest.ProtoReflect.Descriptor instead.
func (*DeregisterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{2}
}

func (x *DeregisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeregisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeregisterResponse) Reset() {
	*x = DeregisterResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeregisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeregisterResponse) ProtoMessage() {}

func (x *DeregisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeregisterResponse.ProtoReflect.Descriptor instead.
func (*DeregisterResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{3}
}

func (x *DeregisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{4}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type GetAgentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        AgentStatus            `protobuf:"varint,1,opt,name=status,proto3,enum=a2a.AgentStatus" json:"status,omitempty"`
	Capability    string                 `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{6}
}

func (x *ListAgentsRequest) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *ListAgentsRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *ListAgentsRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type DiscoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverRequest) Reset() {
	*x = DiscoverRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverRequest) ProtoMessage() {}

func (x *DiscoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverRequest.ProtoReflect.Descriptor instead.
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{8}
}

func (x *DiscoverRequest) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

type DiscoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoverResponse) Reset() {
	*x = DiscoverResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoverResponse) ProtoMessage() {}

func (x *DiscoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoverResponse.ProtoReflect.Descriptor instead.
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{9}
}

func (x *DiscoverResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Status        AgentStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=a2a.AgentStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{11}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional filter for specific capabilities
	Capabilities  []string `protobuf:"bytes,1,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_api_proto_registry_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{12}
}

func (x *WatchRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type WatchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Event         WatchResponse_EventType `protobuf:"varint,1,opt,name=event,proto3,enum=a2a.WatchResponse_EventType" json:"event,omitempty"`
	Agent         *Agent                  `protobuf:"bytes,2,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_api_proto_registry_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_registry_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_registry_proto_rawDescGZIP(), []int{13}
}

func (x *WatchResponse) GetEvent() WatchResponse_EventType {
	if x != nil {
		return x.Event
	}
	return WatchResponse_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

var File_api_proto_registry_proto protoreflect.FileDescriptor

const file_api_proto_registry_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/registry.proto\x12\x03a2a\x1a\x16api/proto/common.proto\"\xec\x01\n" +
	"\x0fRegisterRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12)\n" +
	"\bendpoint\x18\x04 \x01(\v2\r.a2a.EndpointR\bendpoint\x123\n" +
	"\fcapabilities\x18\x05 \x03(\v2\x0f.a2a.CapabilityR\fcapabilities\x12)\n" +
	"\bmetadata\x18\x06 \x01(\v2\r.a2a.MetadataR\bmetadata\"O\n" +
	"\x10RegisterResponse\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12 \n" +
	"\x05agent\x18\x02 \x01(\v2\n" +
	".a2a.AgentR\x05agent\".\n" +
	"\x11DeregisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\".\n" +
	"\x12DeregisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"4\n" +
	"\x10GetAgentResponse\x12 \n" +
	"\x05agent\x18\x01 \x01(\v2\n" +
	".a2a.AgentR\x05agent\"q\n" +
	"\x11ListAgentsRequest\x12(\n" +
	"\x06status\x18\x01 \x01(\x0e2\x10.a2a.AgentStatusR\x06status\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"8\n" +
	"\x12ListAgentsResponse\x12\"\n" +
	"\x06agents\x18\x01 \x03(\v2\n" +
	".a2a.AgentR\x06agents\"1\n" +
	"\x0fDiscoverRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\"6\n" +
	"\x10DiscoverResponse\x12\"\n" +
	"\x06agents\x18\x01 \x03(\v2\n" +
	".a2a.AgentR\x06agents\"-\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"W\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12(\n" +
	"\x06status\x18\x02 \x01(\x0e2\x10.a2a.AgentStatusR\x06status\"2\n" +
	"\fWatchRequest\x12\"\n" +
	"\fcapabilities\x18\x01 \x03(\tR\fcapabilities\"\xfe\x01\n" +
	"\rWatchResponse\x122\n" +
	"\x05event\x18\x01 \x01(\x0e2\x1c.a2a.WatchResponse.EventTypeR\x05event\x12 \n" +
	"\x05agent\x18\x02 \x01(\v2\n" +
	".a2a.AgentR\x05agent\"\x96\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EVENT_TYPE_REGISTERED\x10\x01\x12\x1b\n" +
	"\x17EVENT_TYPE_DEREGISTERED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_UPDATED\x10\x03\x12\x1d\n" +
	"\x19EVENT_TYPE_HEALTH_CHANGED\x10\x042\xa8\x03\n" +
	"\x0fRegistryService\x127\n" +
	"\bRegister\x12\x14.a2a.RegisterRequest\x1a\x15.a2a.RegisterResponse\x12=\n" +
	"\n" +
	"Deregister\x12\x16.a2a.DeregisterRequest\x1a\x17.a2a.DeregisterResponse\x127\n" +
	"\bGetAgent\x12\x14.a2a.GetAgentRequest\x1a\x15.a2a.GetAgentResponse\x12=\n" +
	"\n" +
	"ListAgents\x12\x16.a2a.ListAgentsRequest\x1a\x17.a2a.ListAgentsResponse\x127\n" +
	"\bDiscover\x12\x14.a2a.DiscoverRequest\x1a\x15.a2a.DiscoverResponse\x12:\n" +
	"\tHeartbeat\x12\x15.a2a.HeartbeatRequest\x1a\x16.a2a.HeartbeatResponse\x120\n" +
	"\x05Watch\x12\x11.a2a.WatchRequest\x1a\x12.a2a.WatchResponse0\x01B,Z*github.com/Sithumli/Beacon/api/proto;protob\x06proto3"

var (
	file_api_proto_registry_proto_rawDescOnce sync.Once
	file_api_proto_registry_proto_rawDescData []byte
)

func file_api_proto_registry_proto_rawDescGZIP() []byte {
	file_api_proto_registry_proto_rawDescOnce.Do(func() {
		file_api_proto_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_registry_proto_rawDesc), len(file_api_proto_registry_proto_rawDesc)))
	})
	return file_api_proto_registry_proto_rawDescData
}

var file_api_proto_registry_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_registry_proto_goTypes = []any{
	(WatchResponse_EventType)(0), // 0: a2a.WatchResponse.EventType
	(*RegisterRequest)(nil),      // 1: a2a.RegisterRequest
	(*RegisterResponse)(nil),     // 2: a2a.RegisterResponse
	(*DeregisterRequest)(nil),    // 3: a2a.DeregisterRequest
	(*DeregisterResponse)(nil),   // 4: a2a.DeregisterResponse
	(*GetAgentRequest)(nil),      // 5: a2a.GetAgentRequest
	(*GetAgentResponse)(nil),     // 6: a2a.GetAgentResponse
	(*ListAgentsRequest)(nil),    // 7: a2a.ListAgentsRequest
	(*ListAgentsResponse)(nil),   // 8: a2a.ListAgentsResponse
	(*DiscoverRequest)(nil),      // 9: a2a.DiscoverRequest
	(*DiscoverResponse)(nil),     // 10: a2a.DiscoverResponse
	(*HeartbeatRequest)(nil),     // 11: a2a.HeartbeatRequest
	(*HeartbeatResponse)(nil),    // 12: a2a.HeartbeatResponse
	(*WatchRequest)(nil),         // 13: a2a.WatchRequest
	(*WatchResponse)(nil),        // 14: a2a.WatchResponse
	(*Endpoint)(nil),             // 15: a2a.Endpoint
	(*Capability)(nil),           // 16: a2a.Capability
	(*Metadata)(nil),             // 17: a2a.Metadata
	(*Agent)(nil),                // 18: a2a.Agent
	(AgentStatus)(0),             // 19: a2a.AgentStatus
}
var file_api_proto_registry_proto_depIdxs = []int32{
	15, // 0: a2a.RegisterRequest.endpoint:type_name -> a2a.Endpoint
	16, // 1: a2a.RegisterRequest.capabilities:type_name -> a2a.Capability
	17, // 2: a2a.RegisterRequest.metadata:type_name -> a2a.Metadata
	18, // 3: a2a.RegisterResponse.agent:type_name -> a2a.Agent
	18, // 4: a2a.GetAgentResponse.agent:type_name -> a2a.Agent
	19, // 5: a2a.ListAgentsRequest.status:type_name -> a2a.AgentStatus
	18, // 6: a2a.ListAgentsResponse.agents:type_name -> a2a.Agent
	18, // 7: a2a.DiscoverResponse.agents:type_name -> a2a.Agent
	19, // 8: a2a.HeartbeatResponse.status:type_name -> a2a.AgentStatus
	0,  // 9: a2a.WatchResponse.event:type_name -> a2a.WatchResponse.EventType
	18, // 10: a2a.WatchResponse.agent:type_name -> a2a.Agent
	1,  // 11: a2a.RegistryService.Register:input_type -> a2a.RegisterRequest
	3,  // 12: a2a.RegistryService.Deregister:input_type -> a2a.DeregisterRequest
	5,  // 13: a2a.RegistryService.GetAgent:input_type -> a2a.GetAgentRequest
	7,  // 14: a2a.RegistryService.ListAgents:input_type -> a2a.ListAgentsRequest
	9,  // 15: a2a.RegistryService.Discover:input_type -> a2a.DiscoverRequest
	11, // 16: a2a.RegistryService.Heartbeat:input_type -> a2a.HeartbeatRequest
	13, // 17: a2a.RegistryService.Watch:input_type -> a2a.WatchRequest
	2,  // 18: a2a.RegistryService.Register:output_type -> a2a.RegisterResponse
	4,  // 19: a2a.RegistryService.Deregister:output_type -> a2a.DeregisterResponse
	6,  // 20: a2a.RegistryService.GetAgent:output_type -> a2a.GetAgentResponse
	8,  // 21: a2a.RegistryService.ListAgents:output_type -> a2a.ListAgentsResponse
	10, // 22: a2a.RegistryService.Discover:output_type -> a2a.DiscoverResponse
	12, // 23: a2a.RegistryService.Heartbeat:output_type -> a2a.HeartbeatResponse
	14, // 24: a2a.RegistryService.Watch:output_type -> a2a.WatchResponse
	18, // [18:25] is the sub-list for method output_type
	11, // [11:18] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_api_proto_registry_proto_init() }
func file_api_proto_registry_proto_init() {
	if File_api_proto_registry_proto != nil {
		return
	}
	file_api_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_registry_proto_rawDesc), len(file_api_proto_registry_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_registry_proto_goTypes,
		DependencyIndexes: file_api_proto_registry_proto_depIdxs,
		EnumInfos:         file_api_proto_registry_proto_enumTypes,
		MessageInfos:      file_api_proto_registry_proto_msgTypes,
	}.Build()
	File_api_proto_registry_proto = out.File
	file_api_proto_registry_proto_goTypes = nil
	file_api_proto_registry_proto_depIdxs = nil
}
